services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nowo\TiptapEditorBundle\Twig\NowoTiptapEditorTwigExtension:
        tags: ['twig.extension']

    Nowo\TiptapEditorBundle\Form\TiptapEditorType:
        arguments:
            $profiles: '%nowo_tiptap_editor.profiles%'
            $defaultProfileName: '%nowo_tiptap_editor.default_profile%'
        tags:
            - { name: form.type }
